using System;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// A small looping preview of one temple rule, played around the selected temple on the level
/// map (leaves drifting, rain streaks, a shake, water rising, the sun going dark).
///
/// Lives on a prefab at Resources/UI/MapRuleFx/MapRuleFx_&lt;LevelRule&gt;, generated by
/// TamalStacker ▸ Temples ▸ Set Up Rule Previews. The look is all in the prefab: every moving
/// part is an Image child listed in <see cref="motes"/>, and the motion values below are what
/// to tune. Nothing is built at runtime.
///
/// Kept deliberately cheap so the map always pans and zooms smoothly: a handful of images, no
/// raycast targets, no allocations per frame, its own nested Canvas so moving the motes
/// re-batches only this effect, and at most one preview (two on a paired temple) runs at a time
/// (<see cref="MapRulePreview"/>). Positions are authored in a <see cref="referenceSize"/> box
/// and the whole effect is scaled to the temple button it sits on.
/// </summary>
public class MapRuleFx : MonoBehaviour
{
    [Serializable]
    public class Mote
    {
        [Tooltip("The moving image. Raycast Target should be off.")]
        public RectTransform target;

        [Tooltip("Faded by the alpha values below. Defaults to the target's own Graphic.")]
        public Graphic graphic;

        [Tooltip("Start and end, in the effect's reference box (0,0 = centre).")]
        public Vector2 from;
        public Vector2 to;

        [Tooltip("Seconds for one pass from start to end.")]
        [Min(0.05f)] public float period = 1.5f;

        [Tooltip("Offset into the loop, 0-1, so copies of a mote don't move in step.")]
        [Range(0f, 1f)] public float phase;

        [Tooltip("Share of the period the mote moves in; it's hidden for the rest (a puff that bursts, then rests).")]
        [Range(0.05f, 1f)] public float activeShare = 1f;

        [Tooltip("Go there and back (water level, moon) instead of restarting at the start (rain, leaves).")]
        public bool pingPong;

        [Tooltip("Ease in and out along the path.")]
        public bool smooth;

        [Tooltip("Sideways sway across the path, in reference units, and how many sways per pass.")]
        public float wobble;
        public float wobbleCycles = 1f;

        [Tooltip("Degrees turned over one pass.")]
        public float spin;

        public float scaleFrom = 1f;
        public float scaleTo = 1f;

        [Range(0f, 1f)] public float alphaFrom = 1f;
        [Range(0f, 1f)] public float alphaTo = 1f;

        [Tooltip("Share of the pass spent fading in and out (0 = no fade). Ignored with Ping Pong.")]
        [Range(0f, 0.5f)] public float fadeIn = 0.15f;
        [Range(0f, 0.5f)] public float fadeOut = 0.15f;

        [NonSerialized] public float baseAlpha = -1f;
        [NonSerialized] public float baseRotation;
    }

    public const string ResourceFolder = "UI/MapRuleFx/";

    public static string ResourcePath(LevelRule rule) => ResourceFolder + "MapRuleFx_" + rule;

    [Tooltip("The box the mote positions are authored in. The effect is scaled so this box matches " +
             "the temple button's size times Size In Buttons.")]
    public Vector2 referenceSize = new Vector2(200f, 200f);

    [Tooltip("How big the effect is compared with the temple button it plays on.")]
    public float sizeInButtons = 1.6f;

    [Tooltip("Shift from the button's centre, in reference units (e.g. up, so a sun sits over the temple).")]
    public Vector2 offset;

    public Mote[] motes = new Mote[0];

    [Header("Temple shake (Cabracán)")]
    [Tooltip("Shake the temple button itself in short bursts. Off for every rule but the quake.")]
    public bool shakeTemple;

    [Tooltip("Largest sideways kick, in reference units.")]
    public float shakeAmplitude = 5f;

    [Tooltip("Seconds from one burst to the next. Give the dust motes the same period so they puff on the burst.")]
    [Min(0.2f)] public float shakeEvery = 2.2f;

    [Tooltip("Seconds each burst lasts.")]
    [Min(0.05f)] public float shakeLength = 0.45f;

    [Tooltip("Kicks per second during a burst.")]
    public float shakeFrequency = 22f;

    private float clock;
    private RectTransform shaken;
    private Vector2 shakenHome;
    private float scale = 1f;

    /// <summary>
    /// Puts the effect over <paramref name="button"/>: same parent and position, sized to it,
    /// drawn in front of it. Starts the loop from the top.
    /// </summary>
    public void Attach(RectTransform button)
    {
        Detach();

        var rt = (RectTransform)transform;
        rt.SetParent(button.parent, false);
        rt.SetSiblingIndex(button.GetSiblingIndex() + 1);
        rt.anchorMin = button.anchorMin;
        rt.anchorMax = button.anchorMax;
        rt.pivot = new Vector2(0.5f, 0.5f);
        rt.sizeDelta = referenceSize;

        // The button's rect size, not its pulse scale, so the effect doesn't breathe with it.
        Vector2 size = button.rect.size;
        float reference = Mathf.Max(1f, Mathf.Max(referenceSize.x, referenceSize.y));
        scale = Mathf.Max(size.x, size.y) * sizeInButtons / reference;
        if (scale <= 0f) scale = 1f;
        rt.localScale = Vector3.one * scale;

        Vector2 centre = button.anchoredPosition + (Vector2.one * 0.5f - button.pivot) * size;
        rt.anchoredPosition = centre + offset * scale;

        if (shakeTemple)
        {
            shaken = button;
            shakenHome = button.anchoredPosition;
        }

        clock = 0f;
        gameObject.SetActive(true);
        Tick(0f);
    }

    /// <summary>Stops the effect and puts a shaken temple back where it was.</summary>
    public void Detach()
    {
        RestoreShaken();
        gameObject.SetActive(false);
    }

    private void OnDisable() => RestoreShaken();

    private void RestoreShaken()
    {
        if (shaken != null) shaken.anchoredPosition = shakenHome;
        shaken = null;
    }

    private void Update() => Tick(Time.unscaledDeltaTime);

    private void Tick(float dt)
    {
        clock += dt;

        for (int i = 0; i < motes.Length; i++)
        {
            Mote m = motes[i];
            if (m == null || m.target == null) continue;
            Animate(m);
        }

        if (shaken != null)
        {
            float inBurst = Mathf.Repeat(clock, shakeEvery);
            float kick = 0f;
            if (inBurst < shakeLength)
            {
                float decay = 1f - inBurst / shakeLength;
                kick = Mathf.Sin(inBurst * shakeFrequency * Mathf.PI * 2f) * shakeAmplitude * decay;
            }
            shaken.anchoredPosition = shakenHome + new Vector2(kick * scale, 0f);
        }
    }

    private void Animate(Mote m)
    {
        if (m.baseAlpha < 0f)
        {
            if (m.graphic == null) m.graphic = m.target.GetComponent<Graphic>();
            m.baseAlpha = m.graphic != null ? m.graphic.color.a : 1f;
            m.baseRotation = m.target.localEulerAngles.z;
        }

        float t = Mathf.Repeat(clock / m.period + m.phase, 1f);
        if (m.activeShare < 1f)
        {
            if (t > m.activeShare)
            {
                if (m.graphic != null && m.graphic.color.a != 0f)
                {
                    Color hidden = m.graphic.color;
                    hidden.a = 0f;
                    m.graphic.color = hidden;
                }
                return;
            }
            t /= m.activeShare;
        }
        float along = m.pingPong ? 1f - Mathf.Abs(t * 2f - 1f) : t;
        if (m.smooth) along = along * along * (3f - 2f * along);

        Vector2 pos = Vector2.LerpUnclamped(m.from, m.to, along);
        if (m.wobble != 0f)
        {
            Vector2 dir = m.to - m.from;
            Vector2 side = dir.sqrMagnitude > 0.0001f ? new Vector2(-dir.y, dir.x).normalized : Vector2.right;
            pos += side * (Mathf.Sin(t * m.wobbleCycles * Mathf.PI * 2f) * m.wobble);
        }
        m.target.anchoredPosition = pos;

        if (m.spin != 0f) m.target.localRotation = Quaternion.Euler(0f, 0f, m.baseRotation + m.spin * t);

        float s = Mathf.LerpUnclamped(m.scaleFrom, m.scaleTo, along);
        m.target.localScale = new Vector3(s, s, 1f);

        if (m.graphic != null)
        {
            float a = Mathf.Lerp(m.alphaFrom, m.alphaTo, along);
            if (!m.pingPong)
            {
                if (m.fadeIn > 0f && t < m.fadeIn) a *= t / m.fadeIn;
                if (m.fadeOut > 0f && t > 1f - m.fadeOut) a *= (1f - t) / m.fadeOut;
            }
            Color c = m.graphic.color;
            c.a = m.baseAlpha * a;
            m.graphic.color = c;
        }
    }
}
